language: php

sudo: false

matrix:
  include:
    - php: '7.0'
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: '7.0'
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: '5.6'
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: '5.6'
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=latest
    - php: 'hhvm'
      env: WP_VERSION=latest
    - php: '5.6'
      env: WP_VERSION=4.0
    - php: '5.5'
      env: WP_VERSION=4.0
    - php: '5.4'
      env: WP_VERSION=4.0
    - php: 'hhvm'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.3'
      env: WP_VERSION=4.0

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

addons:
    code_climate:
        repo_token: 05d667182ba1050b131eac61db170f2dab371382ee960ad39e78a91ed96f752c
