language: php
dist: xenial

services:
    - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - WP_VERSION=latest
  - WP_VERSION=5.3

matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.4
      env: WP_VERSION=latest RUN_PHPCS=1
    - name: Code Coverage
      php: 7.1
      env: WP_VERSION=latest RUN_CODE_COVERAGE=1
    - name: Bleeding Edge
      php: nightly
      env: WP_VERSION=trunk
  allow_failures:
    - name: Code Coverage
    - name: Bleeding Edge

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer update --prefer-source --prefer-lowest --no-interaction --no-ansi
    else
      composer install --prefer-source --no-interaction --no-ansi
    fi
  - bash vendor/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
      chmod +x coveralls.phar
      mkdir -p build/logs
    fi

script:
  - |
    if [[ ${RUN_PHPCS} ]]; then
      ./vendor/bin/phpcs
    elif [[ ${RUN_CODE_COVERAGE} ]]; then
      phpdbg -qrr ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=build/logs/clover.xml
    else
      WP_MULTISITE=0 ./vendor/bin/phpunit
      WP_MULTISITE=1 ./vendor/bin/phpunit
    fi

after_success:
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      travis_retry php coveralls.phar
    fi
